"""empty message

Revision ID: 8f95951d6e92
Revises: 6277e53fcc9f
Create Date: 2022-01-20 21:41:26.241365

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8f95951d6e92'
down_revision = '6277e53fcc9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('destacado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('colaborador', sa.String(length=200), nullable=False),
    sa.Column('colab_id', sa.Integer(), nullable=False),
    sa.Column('organizacion', sa.String(length=200), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('login_info', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['login_info'], ['login.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('colab_id'),
    sa.UniqueConstraint('colaborador'),
    sa.UniqueConstraint('login_info'),
    sa.UniqueConstraint('org_id'),
    sa.UniqueConstraint('organizacion')
    )
    op.create_table('datos_banco',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_banco', sa.String(length=100), nullable=False),
    sa.Column('num_cuenta', sa.String(length=20), nullable=False),
    sa.Column('phone', sa.String(length=100), nullable=False),
    sa.Column('name_zelle', sa.String(length=200), nullable=False),
    sa.Column('email_zelle', sa.String(length=200), nullable=False),
    sa.Column('bank_name', sa.String(length=200), nullable=False),
    sa.Column('account_number', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('swift', sa.String(length=100), nullable=False),
    sa.Column('abba', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=100), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizacion.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bank_name'),
    sa.UniqueConstraint('email_zelle'),
    sa.UniqueConstraint('name_zelle'),
    sa.UniqueConstraint('org_id')
    )
    op.drop_index('colab_id', table_name='destacados')
    op.drop_index('colaborador', table_name='destacados')
    op.drop_index('org_id', table_name='destacados')
    op.drop_index('organizacion', table_name='destacados')
    op.drop_table('destacados')
    op.add_column('colaboracion', sa.Column('help_type', sa.Enum('DINERO', 'INSUMOS', 'TRANSPORTE', 'PARTICIPACION', name='tipoayuda'), nullable=False))
    op.add_column('colaboracion', sa.Column('help_status', sa.Enum('ENVIADA', 'PROCESO', 'RECIBIDA', 'FAIL', name='statuscolaboracion'), nullable=False))
    op.create_foreign_key(None, 'colaboracion', 'colaborador', ['colab_id'], ['id'])
    op.add_column('colaborador', sa.Column('login_info', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'colaborador', ['login_info'])
    op.create_foreign_key(None, 'colaborador', 'login', ['login_info'], ['id'])
    op.add_column('organizacion', sa.Column('login_info', sa.Integer(), nullable=False))
    op.add_column('organizacion', sa.Column('org_type', sa.Enum('CASAHOGAR', 'ANCIANATO', 'OTRAS', name='tipoorg'), nullable=False))
    op.create_unique_constraint(None, 'organizacion', ['login_info'])
    op.create_foreign_key(None, 'organizacion', 'login', ['login_info'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organizacion', type_='foreignkey')
    op.drop_constraint(None, 'organizacion', type_='unique')
    op.drop_column('organizacion', 'org_type')
    op.drop_column('organizacion', 'login_info')
    op.drop_constraint(None, 'colaborador', type_='foreignkey')
    op.drop_constraint(None, 'colaborador', type_='unique')
    op.drop_column('colaborador', 'login_info')
    op.drop_constraint(None, 'colaboracion', type_='foreignkey')
    op.drop_column('colaboracion', 'help_status')
    op.drop_column('colaboracion', 'help_type')
    op.create_table('destacados',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('colaborador', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('colab_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('organizacion', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('org_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('organizacion', 'destacados', ['organizacion'], unique=False)
    op.create_index('org_id', 'destacados', ['org_id'], unique=False)
    op.create_index('colaborador', 'destacados', ['colaborador'], unique=False)
    op.create_index('colab_id', 'destacados', ['colab_id'], unique=False)
    op.drop_table('datos_banco')
    op.drop_table('destacado')
    # ### end Alembic commands ###
