"""empty message

Revision ID: a5080c922fc8
Revises: 
Create Date: 2022-01-21 19:20:08.636299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5080c922fc8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('user_type', sa.Enum('ORGANIZATION', 'PARTICULAR', 'BUSINESS', name='usertype'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('password')
    )
    op.create_table('collaborator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=100), nullable=False),
    sa.Column('anonymus', sa.Boolean(), nullable=False),
    sa.Column('login_info', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['login_info'], ['login.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login_info')
    )
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collaborator_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('login_info', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['login_info'], ['login.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collaborator_id'),
    sa.UniqueConstraint('login_info'),
    sa.UniqueConstraint('organization_id')
    )
    op.create_table('organization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_name', sa.String(length=200), nullable=False),
    sa.Column('rif', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('person_oncharge', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('login_info', sa.Integer(), nullable=False),
    sa.Column('organization_type', sa.Enum('CHILDREN', 'ELDERLY', 'OTHERS', name='organization_type'), nullable=False),
    sa.ForeignKeyConstraint(['login_info'], ['login.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login_info'),
    sa.UniqueConstraint('organization_name'),
    sa.UniqueConstraint('person_oncharge'),
    sa.UniqueConstraint('rif')
    )
    op.create_table('aid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collaborator_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('help_type', sa.Enum('MONEY', 'SUPPLIES', 'TRANSPORT', 'PARTICIPATION', name='helptype'), nullable=False),
    sa.Column('help_status', sa.Enum('SEND', 'ONGOING', 'RECEIVED', 'FAIL', name='colaborationstatus'), nullable=False),
    sa.ForeignKeyConstraint(['collaborator_id'], ['collaborator.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collaborator_id'),
    sa.UniqueConstraint('organization_id')
    )
    op.create_table('bank_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_name_national', sa.String(length=100), nullable=False),
    sa.Column('account_number_national', sa.String(length=20), nullable=False),
    sa.Column('phone', sa.String(length=100), nullable=False),
    sa.Column('name_zelle', sa.String(length=200), nullable=False),
    sa.Column('email_zelle', sa.String(length=200), nullable=False),
    sa.Column('bank_name_international', sa.String(length=200), nullable=False),
    sa.Column('account_number_international', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('swift', sa.String(length=100), nullable=False),
    sa.Column('abba', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=100), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bank_name_international'),
    sa.UniqueConstraint('email_zelle'),
    sa.UniqueConstraint('name_zelle'),
    sa.UniqueConstraint('org_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bank_data')
    op.drop_table('aid')
    op.drop_table('organization')
    op.drop_table('favorite')
    op.drop_table('collaborator')
    op.drop_table('login')
    # ### end Alembic commands ###
