"""empty message

Revision ID: f3aa090162fa
Revises: 
Create Date: 2022-01-29 13:12:56.624643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3aa090162fa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('user_type', sa.Enum('ORGANIZATION', 'PARTICULAR', 'BUSINESS', name='usertype'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('aider',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=100), nullable=False),
    sa.Column('anonymus', sa.Boolean(), nullable=False),
    sa.Column('user_info', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_info'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_info')
    )
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aider_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('user_info', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_info'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aider_id'),
    sa.UniqueConstraint('organization_id'),
    sa.UniqueConstraint('user_info')
    )
    op.create_table('organization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_name', sa.String(length=200), nullable=False),
    sa.Column('rif', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('person_oncharge', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('user_info', sa.Integer(), nullable=False),
    sa.Column('organization_type', sa.Enum('CHILDREN', 'ELDERLY', 'OTHERS', name='organization_type'), nullable=False),
    sa.ForeignKeyConstraint(['user_info'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_name'),
    sa.UniqueConstraint('person_oncharge'),
    sa.UniqueConstraint('rif'),
    sa.UniqueConstraint('user_info')
    )
    op.create_table('aid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aider_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('help_type', sa.Enum('MONEY', 'SUPPLIES', 'TRANSPORT', 'PARTICIPATION', name='helptype'), nullable=False),
    sa.Column('help_status', sa.Enum('SEND', 'ONGOING', 'RECEIVED', 'FAIL', name='colaborationstatus'), nullable=False),
    sa.ForeignKeyConstraint(['aider_id'], ['aider.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aider_id'),
    sa.UniqueConstraint('organization_id')
    )
    op.create_table('bank_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_name_national', sa.String(length=100), nullable=False),
    sa.Column('account_number_national', sa.String(length=20), nullable=False),
    sa.Column('phone', sa.String(length=100), nullable=False),
    sa.Column('name_zelle', sa.String(length=200), nullable=False),
    sa.Column('email_zelle', sa.String(length=200), nullable=False),
    sa.Column('bank_name_international', sa.String(length=200), nullable=False),
    sa.Column('account_number_international', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('swift', sa.String(length=100), nullable=False),
    sa.Column('abba', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=100), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bank_name_international'),
    sa.UniqueConstraint('email_zelle'),
    sa.UniqueConstraint('name_zelle'),
    sa.UniqueConstraint('org_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bank_data')
    op.drop_table('aid')
    op.drop_table('organization')
    op.drop_table('favorite')
    op.drop_table('aider')
    op.drop_table('user')
    # ### end Alembic commands ###
